name: The coolest workflow on GitHub
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          pip install flake8
          flake8 src tests

  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt' )}}
          restore-keys: ${{ runner.os }}-pip-
      
      - name: Set up Python
        uses: ./.github/actions/setup-python-env
        with:
          python-version: 3.12
          requirements-path: 'requirements.txt'

      - name: lint 
        run: make lint

      - name: test
        run: pytest --junitxml=tests/output/results.xml --maxfail=1 --disable-warnings -q

      - name: upload test results
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./tests/output

      