name: The coolest workflow on GitHub
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: lint 
        run: make lint

      - name: test
        run: pytest --maxfail=1 --disable-warnings -q

      